### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by mrAceT** [openwanderer/jsapi#1]
Would it be an idea to add a "index[1-9].html" containing a simple working examples of the code, ranging from "ultra basic" to more advanced?

**Comment by nickw1** [comment]
@mrAceT yes I think so. If you look at the server repo I am already doing that, but at the moment you have to install the PHP-based server to view them. It's a good idea to put (some of) the examples - the ones which don't depend on the back end - here instead. Will do this when I have a moment.

**Comment by nickw1** [comment]
@mrAceT ...have added one example showing basic usage of `OpenWanderer.Viewer` to add markers and a polyline using lat, lon and elevation. Other examples (e.g. sequence navigation) will likely need a server component too so will be more complex - these will follow.

**Comment by nickw1** [comment]
A range of examples now included, both client-only and client/server. Closing this for now as I think I have covered most of what you can do with the API as it stands at the moment.
